### ISSUE TITLE
Send message once after state change

### ISSUE THREAD

**Issue by Schroedingberg** [Ali-Toosi/django-tgbot#10]
This is related to [another issue](https://github.com/Ali-Toosi/django-tgbot_demo/issues/2) about notification style messages. However, this issue is more specific, which hopefully makes the development easier.

The functionality that I propose sounds rather straightforward: Some kind of option, maybe associated with processors, that if activated will send a message directly after the state has changed rather than only as an answer to a user message.

One way might be to simulate user input somehow, but I have not found out so far how to do this and it sounds overly complicated. 

I need this functionality because I am working on project that is heavily based upon this package:

I am building a django app that allows e.g. journalists to build bots (using the admin interface) without having to code, to be able to use telegram bots as a publishing channel for their content. This might almost sound like a standard telegram channel, but the difference is, that subscribers can set personal preferences on how deep they want to dig into a certain topic, how often they want to receive articles and at which time of the day (which is implemented with django-celery beat).  This allows for a more immersive experience of journalistic content, at least that is the idea.

I will keep on trying to solve this issue and of course publish any results. Once I get all of this working, I might also add an example bot builder application to the examples repository, I guess that would be an interesting piece of code to look at.
I have a feeling that this whole project is much harder than I expected, so any help is appreciated ;-)

**Comment by Ali-Toosi** [comment]
Thanks for opening this. Yeah it definitely sounds like something useful. I'll have it in mind for the next round of development here.
On a side note, another thing that I have been wanting to work on was the ability to create several bots with the same code but different usernames (i.e. brands). I thought that was quite complex with the current state of the package but I'm surprised you are doing it already. Would you mind sharing how you've gone about it?

P.S. I think your idea is really good. If you manage to develop it generic enough, you can also easily extend it to work with almost any source of information. One that I have in mind is a bot that works Reddit subs. Or possibly even RSS feeds of news websites or anything.

**Comment by Schroedingberg** [comment]
> the ability to create several bots with the same code but different usernames (i.e. brands). I thought that was quite complex with the current state of the package but I'm surprised you are doing it already. Would you mind sharing how you've gone about it?

I would love to, but I'm not sure whether I actually did what you described. But maybe I just do not understand the question right.

**Comment by Ali-Toosi** [comment]
You mentioned journalists can create a bot from Django admin. What happens when they create a new bot? Do you create a new app inside your Django project for them? DO they use the same bot you have registered with @BotFather and only set it to post in their channel? Or do they connect their own bot's webhook to your project and it starts working?

**Comment by Schroedingberg** [comment]
The creation itself is currently not in scope, this is considered an admin task, i.e. some tech savy person creates a new django app.  After that, the journalist uses the webapp to feed content to the bot and (visually) program its behaviour. Automatic creation of bots is probably going to be a whole new project on its own.
