### ISSUE TITLE
get_id AttributeError

### ISSUE THREAD

**Issue by liorisakov** [Ali-Toosi/django-tgbot#15]
Hi, I keep on getting:
<html>
<body>

Exception Value: | 'NoneType' object has no attribute 'get_id'
-- | --

</body>
</html>
Any idea why?

**Comment by Ali-Toosi** [comment]
Hi, can you put all of your code please?

**Comment by Ali-Toosi** [comment]
I'm closing this issue but I'm guessing you're getting the "user" object somewhere it doesn't exist then try getting the id of it. Refer to Telegram bot API to check what fields are optional and what is not.
