### ISSUE TITLE
Please consider web app future?

### ISSUE THREAD

**Issue by eba-alemayehu** [Ali-Toosi/django-tgbot#18]
I don't know if you have noticed telegram has new bot future called Web Apps https://core.telegram.org/bots/webapps 

Please consider it on this package.

**Comment by jeromepacman** [comment]
Repo is archived  .. 🤷‍♂️

**Comment by Ali-Toosi** [comment]
Hi,
As Jerome has mentioned above, I'm thinking about archiving this repo as https://github.com/aiogram/aiogram is now offering all the ideas implemented in this package and it's actually being maintained so there might not be a lot of reasons to keep this going. I might create a Django package based on aiogram in future but either way, it's unlikely that more features would be added to django-tgbot.
