### ISSUE TITLE
Could bots be in a custom module?

### ISSUE THREAD

**Issue by pwqw** [Ali-Toosi/django-tgbot#3]
https://github.com/Ali-Toosi/django-tgbot/blob/94d2a54acf233822f3d44dc7ac86afd9e0857a65/django_tgbot/management/commands/tgbotwebhook.py#L16

Such as: 
```
project
 |- apps
 |    |- app1
 |    |- app2
 |- bots
 |    |- foobot
 |    |- barbot
 |- settings.py
 |- manage.py
```
``` python
# settings.py
TGBOT_BASE_DIR = os.path.join(settings.BASE_DIR, 'bots')

# tgbotwebhook.py:L16
dst = os.path.join(settings.TGBOT_BASE_DIR,  bot_username)
```

**Comment by Ali-Toosi** [comment]
Interesting suggestion. I'll add it in a future release.

**Comment by pwqw** [comment]
Ahh but if it only affects the manage.py commands, it is not even an issue. I could even close it.
I leave it at your mercy. Thank you.
