### ISSUE TITLE
Forward a message to a channel and reply to that message

### ISSUE THREAD

**Issue by pydevup** [Ali-Toosi/django-tgbot#5]
Thank you for your api, like django it is  fast developing.
My question is how it is possible to forward a message to a channel by bot and then immediately reply to that message.
i know when you forward a message, telegram replies with a response but i cant get that response so that i can reply to forwarded message.

**Comment by Ali-Toosi** [comment]
Hi,
Sorry for the late reply.. a couple of busy weeks.
In general, this is how you can send a message (or forward it) and then use the sent message to reply to it:
```
@processor(state_manager, from_states=state_types.All)
def hello_world(bot: TelegramBot, update: Update, state: TelegramState):
    message = bot.sendMessage(update.get_chat().get_id(), 'Hello!')
    message = bot.forwardMessage(update.get_chat().get_id(), update.get_chat().get_id(), message.get_message_id())
    bot.sendMessage(update.get_chat().get_id(), "Reply", reply_to_message_id=message.get_message_id())
```
Add this ^ as one of your processors and all updates will be responded by a message from the bot, which will be forwarded to the same chat by the bot and finally the forwarded message will be replied by the bot:
![Screen Shot 2020-11-10 at 03 36 13](https://user-images.githubusercontent.com/3009161/98571828-0aee4f80-2309-11eb-882a-ef59288ce122.png)

However, your specific case (doing the same scenario but in a channel) made me realize there is actually an error regarding receiving the messages from the channel so you might have faced an integrity error exception. My apologies for that; it is fixed now (it is not versioned yet though - you can either download the updated code from Github or wait a few days before you can download the new version through pip). After downloading the fix, the same code snippet as above would do the same thing in channels:
![Screen Shot 2020-11-10 at 03 50 07](https://user-images.githubusercontent.com/3009161/98572111-5a348000-2309-11eb-9f90-cc4f6bef7f8b.png)

I've reopened this issue till the new version is released and downloadable through pip. Please close it after you have downloaded it (either through pip or Github) and what you wanted to achieve is achieved.

Let me know if there are any other issues. Also, feel free to join our discussion chat (link in repo Readme).

**Comment by Ali-Toosi** [comment]
You may now upgrade to django-tgbot_1.4.9 and the issue will be fixed.
```
pip3 install --upgrade django-tgbot
```
