### ISSUE TITLE
What about type Command?

### ISSUE THREAD

**Issue by blacktyger** [Ali-Toosi/django-tgbot#9]
How to use /command type of text from telegram? Like /start or /help

**Comment by Ali-Toosi** [comment]
Commands are basically text messages that start with / character. There is no additional type defined for them. Could be potentially added in future though as it has been suggested by other people too.

**Comment by blacktyger** [comment]
> Commands are basically text messages that start with / character. There is no additional type defined for them. Could be potentially added in future though as it has been suggested by other people too.

Oh my... I'd never even bother you if only _startswith()_ would come to my mind earlier :D. 

Thanks for your code, I'm going to use it as a starting point to backend telegram crypto currency tip bot :) 

Take care!
